(() => {
  "use strict";
  const $ = selector => document.querySelector(selector);
  const clone = value => JSON.parse(JSON.stringify(value));
  const BASE_DIALOGUES = { welcome:["欢迎回来，今天也一起玩吧！"], hello:["你也好呀"], talk:["今天过得怎么样？"], pat:["嘿嘿，好温柔呀"], gift:["哇！是送给我的吗？"], dress:["换好啦"], zoom:["找我过来干嘛？"], zoomBack:["好啦，我回去啦。"], switch:["换我来陪你吧！"] };
  const BASE_EFFECTS = { welcome:"fade", hello:"shakeX", talk:"zoomPulse", pat:"moveY", gift:"bounce", dress:"sparkle", zoom:"zoomPulse", zoomBack:"fade", switch:"fade" };
  const BASE_PARTICLES = { welcome:"none", hello:"none", talk:"none", pat:"hearts", gift:"candyMix", dress:"sparkle", zoom:"none", zoomBack:"none", switch:"sparkle" };
  const BASE_CHARACTER = { id:"character-1", name:"小桃", accent:"#e96d98", x:2, y:10, scale:1.8, zoomScale:1.45, zoomX:0, zoomY:6, selectorImage:"", selectorNameX:8, selectorNameY:78, outfits:[{name:"樱花常服",path:"assets/character-default.png"},{name:"蓝色制服",path:"assets/character-outfit.png"}], dialogues:BASE_DIALOGUES, effects:BASE_EFFECTS, particles:BASE_PARTICLES };
  const DEFAULT_CONFIG = {
    version:14, title:"", eyebrow:"【Coki牌】俺家OC！", hint:"",
    startScreen:{enabled:true,backgroundImage:"",backgroundPosition:"center",foregroundImage:"",foregroundX:50,foregroundY:48,foregroundScale:1,title:"",subtitle:"【Coki牌】俺家OC！",prompt:"点击任意按钮开始游戏",textColor:"#ffffff",shadeColor:"#000000",shadeOpacity:.16},
    audio:{music:"",sounds:{tap:"",happy:"",magic:""},defaultMusicVolume:.6,defaultSfxVolume:.8},
    settings:{revision:2,musicEnabled:true,sfxEnabled:true,vibrationEnabled:true,motionEnabled:true},
    credits:{title:"制作人员",developer:"请在编辑器中填写开发者",art:"请在编辑器中填写美术素材来源",audio:"请在编辑器中填写音乐与音效素材来源",version:"1.0.0"},
    theme:{accent:"#e96d98",accentDark:"#c94f7c",text:"#674653",buttonBackground:"rgba(255,255,255,.86)",backgroundImage:"",backgroundPosition:"center",backgroundTop:"#fff8f5",backgroundMiddle:"#fbe2ec",backgroundBottom:"#dcebf6"},
    speech:{x:50,y:65,width:260,autoHeight:true,height:58,fontSize:14,textColor:"#704a58",background:"#ffffff",backgroundOpacity:.94,borderColor:"#e96d98",borderWidth:1,radius:18,nameX:18,nameY:-8,nameColor:"#ffffff",nameFontSize:14,nameGlowColor:"#e96d98"},
    buttons:[
      {id:"hello",iconKey:"hello",label:"打招呼",backgroundMode:"default",x:14,y:82,width:78,height:52,visible:true},
      {id:"talk",iconKey:"talk",label:"对话",backgroundMode:"default",x:38,y:82,width:78,height:52,visible:true},
      {id:"pat",iconKey:"pat",label:"摸摸头",backgroundMode:"default",x:62,y:82,width:78,height:52,visible:true},
      {id:"gift",iconKey:"gift",label:"送礼物",backgroundMode:"default",x:86,y:82,width:78,height:52,visible:true},
      {id:"zoom",iconKey:"zoom",label:"过来",backgroundMode:"default",x:28,y:91,width:132,height:52,visible:true},
      {id:"dress",iconKey:"dress",label:"换装",backgroundMode:"default",x:72,y:91,width:132,height:52,visible:true}
    ], characters:[BASE_CHARACTER], defaultCharacterId:"character-1"
  };
  const EFFECTS=["none","shakeX","moveY","zoomPulse","bounce","tilt","fade","spin","sparkle"];
  const ICONS={
    hello:'<path d="M8 11V5.5a1.5 1.5 0 0 1 3 0V9m0-4.5a1.5 1.5 0 0 1 3 0V9m0-3a1.5 1.5 0 0 1 3 0v5m0-2a1.5 1.5 0 0 1 3 0v3c0 5-3.2 8-8 8h-1c-2.4 0-4.2-1.1-5.6-3L3 13.7a1.6 1.6 0 0 1 2.5-2L8 14"/><path d="M4 5 2.5 3.5M6 3V1M2 8H0"/>',
    talk:'<path d="M20 15a4 4 0 0 1-4 4H8l-5 3 1.4-4.2A7 7 0 0 1 2 12V8a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"/><path d="M7 10h.01M11 10h.01M15 10h.01"/>',
    pat:'<path d="M7 12V7a1.5 1.5 0 0 1 3 0v3m0-5a1.5 1.5 0 0 1 3 0v5m0-4a1.5 1.5 0 0 1 3 0v5m0-2a1.5 1.5 0 0 1 3 0v4c0 4.5-2.8 7-7 7h-1c-2.7 0-4.2-1.2-5.6-3.2L3.2 14a1.6 1.6 0 0 1 2.5-2L8 15"/>',
    gift:'<rect x="3" y="9" width="18" height="12" rx="2"/><path d="M12 9v12M2 9h20V6H2zM12 6H7.5A2.5 2.5 0 1 1 10 3.5zM12 6h4.5A2.5 2.5 0 1 0 14 3.5z"/>',
    zoom:'<circle cx="9" cy="8" r="4"/><path d="M2.5 21v-2a5.5 5.5 0 0 1 11 0v2M17 8v6M14 11h6"/>',
    dress:'<path d="M8 4 4 6 2 11l4 2v8h12v-8l4-2-2-5-4-2c-.6 1.4-2 2-4 2S8.6 5.4 8 4z"/>',
    gear:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.1A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3v-4h.1A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.1A1.7 1.7 0 0 0 15.4 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.2.4.6.8 1 1 .3.2.7.3 1.1.3h.1v4h-.1c-.4 0-.8.1-1.1.3-.4.2-.8.6-1 1z"/>',
    switch:'<circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M2.5 20v-1.3A5.7 5.7 0 0 1 8.2 13h.3a5.7 5.7 0 0 1 5.7 5.7V20M14.5 14.2c.7-.5 1.6-.7 2.5-.7h.2a4.3 4.3 0 0 1 4.3 4.3V19"/>',
    credits:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>'
  };
  const iconSvg=key=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${ICONS[key]||ICONS.talk}</svg>`;
  const deepMerge=(base,extra)=>{if(!extra||typeof extra!=="object")return clone(base);const out=Array.isArray(base)?[...base]:{...base};for(const[key,value]of Object.entries(extra))out[key]=value&&typeof value==="object"&&!Array.isArray(value)&&base?.[key]?deepMerge(base[key],value):value;return out;};
  const asLines=(value,fallback)=>Array.isArray(value)?value.map(String).map(v=>v.trim()).filter(Boolean):typeof value==="string"&&value.trim()?value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean):[...fallback];
  const rgba=(color,alpha=1)=>{const value=/^#[0-9a-f]{6}$/i.test(color||"")?color:"#ffffff",n=parseInt(value.slice(1),16),a=Math.min(1,Math.max(0,Number(alpha)));return`rgba(${n>>16},${(n>>8)&255},${n&255},${a})`;};
  const buttonBackground=(button,theme,accent)=>button.backgroundMode==="theme"?accent:button.backgroundMode==="custom"?(button.backgroundColor||theme.buttonBackground):theme.buttonBackground;
  function normalizeCharacter(input,index,fallbackAccent,legacyDialogues,legacyEffects){const source={...BASE_CHARACTER,...(input||{})};source.id=String(source.id||`character-${index+1}`);source.name=String(source.name||`角色 ${index+1}`);source.accent=source.accent||fallbackAccent||DEFAULT_CONFIG.theme.accent;source.outfits=Array.isArray(source.outfits)&&source.outfits.length?source.outfits.map(item=>({...item})):clone(BASE_CHARACTER.outfits);const incoming=input?.dialogues||legacyDialogues||{},keys=new Set([...Object.keys(BASE_DIALOGUES),...Object.keys(incoming)]);source.dialogues={};for(const key of keys)source.dialogues[key]=asLines(incoming[key],BASE_DIALOGUES[key]||["你好呀！"]);source.effects={...BASE_EFFECTS,...(legacyEffects||{}),...(input?.effects||{})};source.particles={...BASE_PARTICLES,...(input?.particles||{})};source.selectorNameX=Number.isFinite(Number(source.selectorNameX))?Number(source.selectorNameX):8;source.selectorNameY=Number.isFinite(Number(source.selectorNameY))?Number(source.selectorNameY):78;return source;}
  function normalizeConfig(raw={}){const config=deepMerge(DEFAULT_CONFIG,raw);config.startScreen={...DEFAULT_CONFIG.startScreen,...(raw.startScreen||{})};config.audio=deepMerge(DEFAULT_CONFIG.audio,raw.audio||{});config.settings={...DEFAULT_CONFIG.settings,...(raw.settings||{})};config.credits={...DEFAULT_CONFIG.credits,...(raw.credits||{})};config.speech={...DEFAULT_CONFIG.speech,...(raw.speech||{})};const incoming=Array.isArray(raw.buttons)?raw.buttons:[],coreIds=new Set(DEFAULT_CONFIG.buttons.map(button=>button.id)),buttons=[];for(const template of DEFAULT_CONFIG.buttons){const saved=incoming.find(item=>item&&item.id===template.id);buttons.push(Object.assign({},template,saved||{}));}for(const saved of incoming){if(!saved?.id||coreIds.has(saved.id))continue;buttons.push(Object.assign({iconKey:"talk",label:"新按钮",x:50,y:74,width:90,height:52,visible:true},saved));}config.buttons=buttons.map(button=>Object.assign({},button,{backgroundMode:button.backgroundMode||(button.backgroundColor?"custom":"default")}));const chars=Array.isArray(raw.characters)&&raw.characters.length?raw.characters:[raw.character||BASE_CHARACTER];config.characters=chars.map((c,i)=>normalizeCharacter(c,i,raw.theme?.accent,raw.dialogues,raw.effects));const ids=new Set();for(const c of config.characters){let id=c.id,s=2;while(ids.has(id))id=`${c.id}-${s++}`;c.id=id;ids.add(id);}config.defaultCharacterId=ids.has(raw.defaultCharacterId)?raw.defaultCharacterId:config.characters[0].id;config.version=16;delete config.character;delete config.dialogues;delete config.effects;return config;}
  const state={config:clone(DEFAULT_CONFIG),characterIndex:0,outfitIndexes:{},zoomed:false,speechTimer:null,toastTimer:null,audioContext:null,musicPlayer:null,preferences:null,gameStarted:false};
  const els={};
  function cacheElements(){for(const id of["game","startScreen","startForeground","startTitle","startSubtitle","startPrompt","character","characterWrap","characterPosition","speech","speakerName","speechText","particles","toast","settingsButton","characterSwitchButton","characterPicker","characterPickerList","buttonRing","outfitGrid","wardrobe","gameTitle","eyebrow","hint","settingsModal","creditsModal","musicEnabled","musicVolume","musicVolumeOut","sfxEnabled","sfxVolume","sfxVolumeOut","vibrationEnabled","motionEnabled","creditsButton","versionText","creditsTitle","creditDeveloper","creditArt","creditAudio","creditsBackButton"])els[id]=$(`#${id}`);}
  async function loadConfig(){try{const response=await fetch(`game-config.json?time=${Date.now()}`);if(!response.ok)throw new Error();state.config=normalizeConfig(await response.json());}catch{state.config=normalizeConfig();}state.characterIndex=Math.max(0,state.config.characters.findIndex(item=>item.id===state.config.defaultCharacterId));state.outfitIndexes={};}
  const activeCharacter=()=>state.config.characters[state.characterIndex]||state.config.characters[0];const outfits=()=>activeCharacter().outfits;const activeOutfitIndex=()=>Math.max(0,Math.min(Number(state.outfitIndexes[activeCharacter().id]||0),outfits().length-1));
  function randomLine(key){const lines=activeCharacter().dialogues[key]||BASE_DIALOGUES[key]||["……"];return lines[Math.floor(Math.random()*lines.length)]||"……";}
  function loadPreferences(){let saved={};try{saved=JSON.parse(localStorage.getItem("gameSettings")||"{}");}catch{}const defaults=state.config.settings||DEFAULT_CONFIG.settings;if(saved.revision!==defaults.revision)saved={};state.preferences={revision:defaults.revision,musicEnabled:saved.musicEnabled??defaults.musicEnabled,sfxEnabled:saved.sfxEnabled??defaults.sfxEnabled,musicVolume:Number(saved.musicVolume??state.config.audio.defaultMusicVolume),sfxVolume:Number(saved.sfxVolume??state.config.audio.defaultSfxVolume),vibration:saved.vibration??defaults.vibrationEnabled,motion:saved.motion??defaults.motionEnabled};savePreferences();}
  function savePreferences(){localStorage.setItem("gameSettings",JSON.stringify(state.preferences));syncSettingsUI();updateMusic();}
  function syncSettingsUI(){const p=state.preferences;if(!p)return;els.musicEnabled.checked=p.musicEnabled;els.sfxEnabled.checked=p.sfxEnabled;els.musicVolume.value=p.musicVolume;els.sfxVolume.value=p.sfxVolume;els.musicVolumeOut.textContent=`${Math.round(p.musicVolume*100)}%`;els.sfxVolumeOut.textContent=`${Math.round(p.sfxVolume*100)}%`;els.vibrationEnabled.checked=p.vibration;els.motionEnabled.checked=p.motion;}
  function updateMusic(){const p=state.preferences,path=state.config.audio.music;if(!p||!path||!state.gameStarted||!p.musicEnabled){state.musicPlayer?.pause();return;}if(!state.musicPlayer||state.musicPlayer.dataset.path!==path){state.musicPlayer?.pause();state.musicPlayer=new Audio(path);state.musicPlayer.dataset.path=path;state.musicPlayer.loop=true;}state.musicPlayer.volume=Math.max(0,Math.min(1,p.musicVolume));state.musicPlayer.play().catch(()=>{});}
  function setIcon(node,key,label=""){node.innerHTML=iconSvg(key);if(label)node.insertAdjacentText("beforeend",label);}
  function applyTheme(){const c=state.config,ch=activeCharacter(),root=document.documentElement.style;root.setProperty("--pink",ch.accent);root.setProperty("--pink-dark",ch.accent);root.setProperty("--ink",c.theme.text);root.setProperty("--button-bg",c.theme.buttonBackground);root.setProperty("--bg-top",c.theme.backgroundTop);root.setProperty("--bg-middle",c.theme.backgroundMiddle);root.setProperty("--bg-bottom",c.theme.backgroundBottom);}
  function applyConfig(){const c=state.config,ch=activeCharacter();applyTheme();document.title=c.title||c.eyebrow||"【Coki牌】俺家OC！";els.gameTitle.textContent=c.title;els.eyebrow.textContent=c.eyebrow;els.hint.textContent=c.hint;if(c.theme.backgroundImage){els.game.classList.add("has-background");els.game.style.setProperty("--background-image",`url("${c.theme.backgroundImage}")`);els.game.style.setProperty("--background-position",c.theme.backgroundPosition||"center");}else els.game.classList.remove("has-background");const start=c.startScreen;els.startTitle.textContent=start.title;els.startSubtitle.textContent=start.subtitle;els.startPrompt.textContent=start.prompt;els.startScreen.style.color=start.textColor;els.startScreen.style.setProperty("--start-shade",rgba(start.shadeColor,start.shadeOpacity));const bg=start.backgroundImage||c.theme.backgroundImage;if(bg){els.startScreen.style.backgroundImage=`url("${bg}")`;els.startScreen.style.backgroundPosition=start.backgroundPosition||"center";}else els.startScreen.style.backgroundImage="";if(start.foregroundImage){els.startForeground.src=start.foregroundImage;els.startForeground.classList.remove("hidden");els.startForeground.style.left=`${start.foregroundX}%`;els.startForeground.style.top=`${start.foregroundY}%`;els.startForeground.style.transform=`translate(-50%,-50%) scale(${start.foregroundScale})`;}else els.startForeground.classList.add("hidden");els.startScreen.classList.toggle("hidden",start.enabled===false);applySpeech();els.characterPosition.style.setProperty("--char-x",`${Number(ch.x)||0}%`);els.characterPosition.style.setProperty("--char-y",`${Number(ch.y)||0}%`);els.characterPosition.style.setProperty("--char-scale",Number(ch.scale)||1);renderButtons();renderWardrobe();renderCharacterPicker();updateUI();els.settingsButton.innerHTML=iconSvg("gear");els.characterSwitchButton.innerHTML=iconSvg("switch");els.characterSwitchButton.classList.toggle("hidden",c.characters.length<2);setIcon(els.creditsButton,"credits","制作人员");els.creditsTitle.textContent=c.credits.title;els.creditDeveloper.textContent=c.credits.developer;els.creditArt.textContent=c.credits.art;els.creditAudio.textContent=c.credits.audio;els.versionText.textContent=`版本 ${c.credits.version}`;}
  function applySpeech(){const s=state.config.speech,ch=activeCharacter(),accent=ch.accent;els.speech.style.left=`${s.x}%`;els.speech.style.top=`${s.y}%`;els.speech.style.width=`${s.width}px`;els.speech.style.height=s.autoHeight?"auto":`${s.height}px`;els.speech.style.fontSize=`${s.fontSize}px`;els.speech.style.color=s.textColor;els.speech.style.backgroundColor=rgba(s.background,s.backgroundOpacity);els.speech.style.border=`${s.borderWidth}px solid ${accent}`;els.speech.style.borderRadius=`${s.radius}px`;els.speakerName.textContent=ch.name;els.speakerName.style.left=`${s.nameX}%`;els.speakerName.style.top=`${s.nameY}px`;els.speakerName.style.color=s.nameColor;els.speakerName.style.fontSize=`${s.nameFontSize}px`;els.speakerName.style.textShadow=`0 0 3px ${accent},0 0 7px ${accent},0 0 12px ${accent}`;const tail=els.speech.querySelector("i");tail.style.backgroundColor=rgba(s.background,s.backgroundOpacity);tail.style.borderRight=`${s.borderWidth}px solid ${accent}`;tail.style.borderBottom=`${s.borderWidth}px solid ${accent}`;}
  function renderButtons(){const c=state.config,accent=activeCharacter().accent;els.buttonRing.replaceChildren();for(const b of c.buttons){const n=document.createElement("button");n.type="button";n.className=`action${["zoom","dress"].includes(b.id)?" action-wide":""}`;n.dataset.action=b.id;const i=document.createElement("b");i.style.color=b.iconColor||accent;if(b.iconImage){const im=document.createElement("img");im.src=b.iconImage;im.alt="";i.append(im);}else i.innerHTML=iconSvg(b.iconKey||"talk");const t=document.createElement("span");t.textContent=b.label;n.append(i,t);Object.assign(n.style,{left:`${b.x}%`,top:`${b.y}%`,width:`${b.width}px`,minHeight:`${b.height}px`,background:buttonBackground(b,c.theme,accent),color:b.textColor||c.theme.text});n.classList.toggle("hidden",b.visible===false);els.buttonRing.append(n);}}
  function updateUI(){els.character.src=outfits()[activeOutfitIndex()].path;syncSettingsUI();updateZoom();}
  function updateZoom(){const c=activeCharacter();els.characterPosition.style.setProperty("--char-zoom",state.zoomed?c.zoomScale:1);els.characterPosition.style.setProperty("--char-zoom-x",state.zoomed?`${c.zoomX}%`:"0%");els.characterPosition.style.setProperty("--char-zoom-y",state.zoomed?`${c.zoomY}%`:"0%");const label=document.querySelector('[data-action="zoom"] span'),button=state.config.buttons.find(item=>item.id==="zoom");if(label&&button)label.textContent=state.zoomed?"好啦":button.label;}
  function renderWardrobe(){els.outfitGrid.replaceChildren();outfits().forEach((o,index)=>{const b=document.createElement("button");b.type="button";b.className="outfit-card";b.dataset.outfit=index;const im=document.createElement("img");im.src=o.path;im.alt=o.name;const s=document.createElement("span");s.textContent=o.name;b.append(im,s);els.outfitGrid.append(b);});}
  function renderCharacterPicker(){els.characterPickerList.replaceChildren();state.config.characters.forEach((c,index)=>{const b=document.createElement("button");b.type="button";b.className=`character-picker-card${index===state.characterIndex?" is-current":""}`;b.dataset.character=index;b.style.setProperty("--card-accent",c.accent);b.style.setProperty("--name-x",`${c.selectorNameX}%`);b.style.setProperty("--name-y",`${c.selectorNameY}%`);const im=document.createElement("img");im.src=c.selectorImage||c.outfits[0]?.path||"";im.alt=c.name;const n=document.createElement("strong");n.textContent=c.name;b.append(im,n);if(index===state.characterIndex){const e=document.createElement("em");e.textContent="当前角色";b.append(e);}els.characterPickerList.append(b);});}
  function switchCharacter(index){if(index===state.characterIndex){closeCharacterPicker();return;}state.characterIndex=Math.max(0,Math.min(index,state.config.characters.length-1));state.zoomed=false;els.speech.classList.add("hidden");applyConfig();closeCharacterPicker();showSpeech(randomLine("switch"),2600);animate(activeCharacter().effects.switch);playTone("tap");}
  function showSpeech(text,duration=2500){clearTimeout(state.speechTimer);els.speechText.textContent=text;els.speech.classList.remove("hidden");state.speechTimer=setTimeout(()=>els.speech.classList.add("hidden"),duration);}function animate(effect){const safe=EFFECTS.includes(effect)?effect:"none";for(const name of EFFECTS)els.characterWrap.classList.remove(`effect-${name}`);if(safe==="none"||!state.preferences.motion)return;void els.characterWrap.offsetWidth;els.characterWrap.classList.add(`effect-${safe}`);setTimeout(()=>els.characterWrap.classList.remove(`effect-${safe}`),900);}function burst(type="none"){if(!state.preferences.motion||type==="none")return;const sets={hearts:["♥","♡"],candy:["🍬","🍭"],sparkle:["✦","✧","✨"],heartsSparkle:["♥","♡","✦","✨"],candyMix:["🍬","🍭","♥","✦"]},symbols=sets[type];if(!symbols)return;const box=els.character.getBoundingClientRect(),gameBox=els.game.getBoundingClientRect(),count=type==="candyMix"?20:14;for(let i=0;i<count;i++){const n=document.createElement("span");n.className="particle";n.textContent=symbols[i%symbols.length];n.style.setProperty("--x",`${box.left-gameBox.left+box.width*(.22+Math.random()*.56)}px`);n.style.setProperty("--y",`${box.top-gameBox.top+box.height*(.24+Math.random()*.5)}px`);n.style.setProperty("--drift",`${-55+Math.random()*110}px`);n.style.setProperty("--turn",`${-90+Math.random()*180}deg`);n.style.setProperty("--size",`${13+Math.random()*15}px`);n.style.setProperty("--color",i%2?activeCharacter().accent:"#fff");els.particles.appendChild(n);setTimeout(()=>n.remove(),1200);}}function trigger(key){showSpeech(randomLine(key));animate(activeCharacter().effects[key]);burst(activeCharacter().particles[key]);}
  function playTone(kind="tap"){if(!state.preferences.sfxEnabled)return;const custom=state.config.audio.sounds?.[kind];if(!custom)return;const player=new Audio(custom);player.volume=Math.max(0,Math.min(1,state.preferences.sfxVolume));player.play().catch(()=>{});}
  const openWardrobe=()=>{els.wardrobe.classList.remove("hidden");playTone("tap");},closeWardrobe=()=>els.wardrobe.classList.add("hidden"),openSettings=()=>{els.settingsModal.classList.remove("hidden");syncSettingsUI();playTone("tap");},closeSettings=()=>els.settingsModal.classList.add("hidden"),openCharacterPicker=()=>{if(state.config.characters.length<2)return;renderCharacterPicker();els.characterPicker.classList.remove("hidden");playTone("tap");},closeCharacterPicker=()=>els.characterPicker.classList.add("hidden");
  function openCredits(){closeSettings();els.creditsModal.classList.remove("hidden");playTone("tap");}function closeCredits(back=false){els.creditsModal.classList.add("hidden");if(back)openSettings();}function selectOutfit(index){state.outfitIndexes[activeCharacter().id]=index;updateUI();trigger("dress");playTone("magic");setTimeout(closeWardrobe,300);}function cycleOutfit(){selectOutfit((activeOutfitIndex()+1)%outfits().length);}function toggleZoom(){state.zoomed=!state.zoomed;updateZoom();trigger(state.zoomed?"zoom":"zoomBack");playTone("tap");}
  const actions={hello(){trigger("hello");playTone("happy");},talk(){trigger("talk");playTone("tap");},pat(){trigger("pat");playTone("happy");},gift(){trigger("gift");playTone("magic");},zoom(){toggleZoom();},dress(){cycleOutfit();}};
  function enterGame(){if(els.startScreen.classList.contains("hidden"))return;els.startScreen.classList.add("is-leaving");state.gameStarted=true;playTone("tap");updateMusic();setTimeout(()=>{els.startScreen.classList.add("hidden");els.startScreen.classList.remove("is-leaving");showSpeech(randomLine("welcome"),2800);animate(activeCharacter().effects.welcome);},360);}
  function bindEvents(){document.addEventListener("click",event=>{if(event.target.closest("#startScreen")){enterGame();return;}if(event.target.closest("[data-close-settings]")){closeSettings();return;}if(event.target.closest("[data-close-credits]")){closeCredits();return;}if(event.target.closest("[data-close-wardrobe]")){closeWardrobe();return;}if(event.target.closest("[data-close-character-picker]")){closeCharacterPicker();return;}const ch=event.target.closest("[data-character]");if(ch){switchCharacter(Number(ch.dataset.character));return;}const outfit=event.target.closest("[data-outfit]");if(outfit){selectOutfit(Number(outfit.dataset.outfit));return;}const button=event.target.closest("[data-action]");if(button){const id=button.dataset.action;if(actions[id])actions[id]();else{trigger(id);playTone("tap");}if(state.preferences.vibration&&navigator.vibrate)navigator.vibrate(18);return;}if(state.gameStarted&&event.target.closest("#game")&&!event.target.closest("#speech,#characterWrap,button,.settings-modal,.credits-modal,.wardrobe,.character-picker")){clearTimeout(state.speechTimer);els.speech.classList.add("hidden");}});els.startScreen.addEventListener("keydown",event=>{if(["Enter"," "].includes(event.key)){event.preventDefault();enterGame();}});els.settingsButton.addEventListener("click",openSettings);els.characterSwitchButton.addEventListener("click",openCharacterPicker);els.creditsButton.addEventListener("click",openCredits);els.creditsBackButton.addEventListener("click",()=>closeCredits(true));els.musicEnabled.addEventListener("change",()=>{state.preferences.musicEnabled=els.musicEnabled.checked;savePreferences();});els.sfxEnabled.addEventListener("change",()=>{state.preferences.sfxEnabled=els.sfxEnabled.checked;savePreferences();if(state.preferences.sfxEnabled)playTone("tap");});els.musicVolume.addEventListener("input",()=>{state.preferences.musicVolume=Number(els.musicVolume.value);savePreferences();});els.sfxVolume.addEventListener("input",()=>{state.preferences.sfxVolume=Number(els.sfxVolume.value);savePreferences();});els.vibrationEnabled.addEventListener("change",()=>{state.preferences.vibration=els.vibrationEnabled.checked;savePreferences();});els.motionEnabled.addEventListener("change",()=>{state.preferences.motion=els.motionEnabled.checked;savePreferences();});document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(!els.characterPicker.classList.contains("hidden"))closeCharacterPicker();else if(!els.creditsModal.classList.contains("hidden"))closeCredits(true);else if(!els.settingsModal.classList.contains("hidden"))closeSettings();else if(!els.wardrobe.classList.contains("hidden"))closeWardrobe();});document.addEventListener("visibilitychange",()=>{if(document.hidden){state.musicPlayer?.pause();if(state.audioContext?.state==="running")state.audioContext.suspend();}else updateMusic();});}
  async function init(){cacheElements();await loadConfig();loadPreferences();applyConfig();bindEvents();if(state.config.startScreen.enabled===false){state.gameStarted=true;updateMusic();setTimeout(()=>{showSpeech(randomLine("welcome"),2800);animate(activeCharacter().effects.welcome);},450);}}
  init();
})();
